[package]
name = "tadli/zenith"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[place]
shared-packages = "game.ReplicatedStorage.Packages"

[dependencies]
# UI Layer
React = "jsdotlua/react@17.1.0"
ReactRoblox = "jsdotlua/react-roblox@17.1.0"

# Logic Layer (ECS)
Jecs = "ukendio/jecs@0.9.0"

# Utils
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.3"

[server-dependencies]
# Networking & Data
ByteNet = "ffrostflame/bytenet@0.4.6"
Janitor = "howmanysmall/janitor@1.18.3"
